name: Ejecutar java

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ejecutar java
        run: |
          javac â€“d out src/*.java
          jar cfe nombre_archivo.jar Main *.class
          java -jar out/Main.jar
          upload-artifact