name: Ejecutar Java

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Compilar código Java
        run: |
          mkdir -p out
          javac -d out src/*.java

      - name: Crear archivo JAR
        run: |
          cd out
          jar cfe app.jar Main *.class
          cd ..

      - name: Ejecutar el programa
        run: |
          java -jar out/app.jar